---
- name: Build Enviroment using Terraform
  hosts: 
   - localhost
  connection: local
  tasks:
  
  - name: test template
    template:
      src: terraform.tfvars.j2
      dest: "terraform-var-file.tf"
